class CfgPatches {
    class jbl_speaker {
        name = "JBL Speaker";
        author = "Raz";
        units[] = {"JBL_Speaker"};
        weapons[] = {};
        requiredVersion = 2.0;
        requiredAddons[] = {"A3_Data_F_Enoch_Loadorder"};
    };
};

class CfgFunctions {
    class JBL {
        tag = "JBL";
        class speaker {
            file = "\jbl_speaker\functions";
            class init {};       // adds actions + JIP catch-up (runs on every machine)
            class command {};    // server: play / stop / next / prev / range
            class syncLocal {};  // client: start/stop the local say3D source
            class trackLoop {};  // server: auto-advance when a track ends
        };
    };
};

// CfgSounds + JBL_Playlist, generated by tools/build_playlist.py
#include "playlist.hpp"

class CfgVehicles {
    class Land_FMradio_F;
    class JBL_Speaker: Land_FMradio_F {
        scope = 2;
        scopeCurator = 2;
        displayName = "JBL Speaker";
        class EventHandlers {
            init = "(_this select 0) call JBL_fnc_init";
        };
    };
};
