#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        author = "Raz";
        units[] = {};
        weapons[] = {};
        requiredVersion = REQUIRED_VERSION;
        requiredAddons[] = {"jbl_common"};
        VERSION_CONFIG;
    };
};

#include "CfgEventHandlers.hpp"

// CfgSounds + jbl_audio_playlist, generated by tools/build_playlist.py
#include "playlist.hpp"
