// Generated by tools/gen_mount_menu.py - do not edit by hand
                    class GVAR(mount) {
                        displayName = "Mount";
                        condition = "[_target, _player] call jbl_common_fnc_canControl";
                        statement = "";
                        class GVAR(mtBackpack) {
                            displayName = "On my body";
                            condition = "(isNull (_player getVariable ['jbl_clippedSpeaker', objNull]) || {(_player getVariable ['jbl_clippedSpeaker', objNull]) == _target}) && {backpack _player != '' || {_target isKindOf 'jbl_partybox'}}";
                            statement = "";
                            class GVAR(mtb_back) {
                                displayName = "Back";
                                condition = "true";
                                statement = "[_target, _player, 'mount', ['backpack', 'back']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(mtb_side) {
                                displayName = "Side (hip)";
                                condition = "!(_target isKindOf 'jbl_partybox')";
                                statement = "[_target, _player, 'mount', ['backpack', 'side']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(mtb_under) {
                                displayName = "Under the backpack";
                                condition = "!(_target isKindOf 'jbl_partybox')";
                                statement = "[_target, _player, 'mount', ['backpack', 'under']] call jbl_speaker_fnc_send";
                            };
                        };
                        class GVAR(mtVehicle) {
                            displayName = "On a vehicle (within 6 m)";
                            condition = "!(!isNull (_target getVariable ['jbl_clippedTo', objNull]))";
                            statement = "";
                            class GVAR(mtv_roof) {
                                displayName = "Roof";
                                condition = "true";
                                statement = "[_target, _player, 'mount', ['vehicle', 'roof']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(mtv_rear) {
                                displayName = "Rear";
                                condition = "true";
                                statement = "[_target, _player, 'mount', ['vehicle', 'rear']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(mtv_front) {
                                displayName = "Front / hood";
                                condition = "true";
                                statement = "[_target, _player, 'mount', ['vehicle', 'front']] call jbl_speaker_fnc_send";
                            };
                        };
                        class GVAR(mtPosBody) {
                            displayName = "Move on my body";
                            condition = "!isNull (_target getVariable ['jbl_clippedTo', objNull])";
                            statement = "";
                            class GVAR(mtpb_back) {
                                displayName = "Back";
                                condition = "true";
                                statement = "[_target, _player, 'mountPos', ['back']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(mtpb_side) {
                                displayName = "Side (hip)";
                                condition = "!(_target isKindOf 'jbl_partybox')";
                                statement = "[_target, _player, 'mountPos', ['side']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(mtpb_under) {
                                displayName = "Under the backpack";
                                condition = "!(_target isKindOf 'jbl_partybox')";
                                statement = "[_target, _player, 'mountPos', ['under']] call jbl_speaker_fnc_send";
                            };
                        };
                        class GVAR(mtPosVehicle) {
                            displayName = "Move on the vehicle";
                            condition = "!isNull (_target getVariable ['jbl_mountedOn', objNull])";
                            statement = "";
                            class GVAR(mtpv_roof) {
                                displayName = "Roof";
                                condition = "true";
                                statement = "[_target, _player, 'mountPos', ['roof']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(mtpv_rear) {
                                displayName = "Rear";
                                condition = "true";
                                statement = "[_target, _player, 'mountPos', ['rear']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(mtpv_front) {
                                displayName = "Front / hood";
                                condition = "true";
                                statement = "[_target, _player, 'mountPos', ['front']] call jbl_speaker_fnc_send";
                            };
                        };
                        class GVAR(mtAdjust) {
                            displayName = "Adjust position";
                            condition = "(!isNull (_target getVariable ['jbl_clippedTo', objNull]) || {!isNull (_target getVariable ['jbl_mountedOn', objNull])})";
                            statement = "";
                            class GVAR(nudge_xp) {
                                displayName = "X +";
                                condition = "true";
                                statement = "[_target, _player, 'nudge', ['x+']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(nudge_xm) {
                                displayName = "X -";
                                condition = "true";
                                statement = "[_target, _player, 'nudge', ['x-']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(nudge_yp) {
                                displayName = "Y +";
                                condition = "true";
                                statement = "[_target, _player, 'nudge', ['y+']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(nudge_ym) {
                                displayName = "Y -";
                                condition = "true";
                                statement = "[_target, _player, 'nudge', ['y-']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(nudge_zp) {
                                displayName = "Z +";
                                condition = "true";
                                statement = "[_target, _player, 'nudge', ['z+']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(nudge_zm) {
                                displayName = "Z -";
                                condition = "true";
                                statement = "[_target, _player, 'nudge', ['z-']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(nudge_rp) {
                                displayName = "Turn right";
                                condition = "true";
                                statement = "[_target, _player, 'nudge', ['r+']] call jbl_speaker_fnc_send";
                            };
                            class GVAR(nudge_rm) {
                                displayName = "Turn left";
                                condition = "true";
                                statement = "[_target, _player, 'nudge', ['r-']] call jbl_speaker_fnc_send";
                            };
                        };
                        class GVAR(mtTakeOff) {
                            displayName = "Take off and put down";
                            condition = "(!isNull (_target getVariable ['jbl_clippedTo', objNull]) || {!isNull (_target getVariable ['jbl_mountedOn', objNull])})";
                            statement = "[_target, _player, 'unmount'] call jbl_speaker_fnc_send";
                        };
                    };
