// Generated by tools/gen_mount_menu.py - do not edit by hand
                class GVAR(cmPosition) {
                    displayName = "Position on my body";
                    condition = "true";
                    statement = "";
                    exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        class GVAR(cmp_back) {
                            displayName = "Back";
                            condition = "true";
                            statement = "[_player, 'mountPos', ['back']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(cmp_side) {
                            displayName = "Side (hip)";
                            condition = "!((_player getVariable ['btspk_clippedSpeaker', objNull]) isKindOf 'btspk_party')";
                            statement = "[_player, 'mountPos', ['side']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(cmp_under) {
                            displayName = "Under the backpack";
                            condition = "!((_player getVariable ['btspk_clippedSpeaker', objNull]) isKindOf 'btspk_party')";
                            statement = "[_player, 'mountPos', ['under']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                };
                class GVAR(cmVehicle) {
                    displayName = "Mount on a vehicle (within 6 m)";
                    condition = "true";
                    statement = "";
                    exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        class GVAR(cmv_roof) {
                            displayName = "Roof";
                            condition = "true";
                            statement = "[_player, 'mount', ['vehicle', 'roof']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(cmv_rear) {
                            displayName = "Rear";
                            condition = "true";
                            statement = "[_player, 'mount', ['vehicle', 'rear']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(cmv_front) {
                            displayName = "Front / hood";
                            condition = "true";
                            statement = "[_player, 'mount', ['vehicle', 'front']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                };
                class GVAR(cmAdjust) {
                    displayName = "Adjust position";
                    condition = "true";
                    statement = "";
                    exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        class GVAR(snudge_xp) {
                            displayName = "X +";
                            condition = "true";
                            statement = "[_player, 'nudge', ['x+']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(snudge_xm) {
                            displayName = "X -";
                            condition = "true";
                            statement = "[_player, 'nudge', ['x-']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(snudge_yp) {
                            displayName = "Y +";
                            condition = "true";
                            statement = "[_player, 'nudge', ['y+']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(snudge_ym) {
                            displayName = "Y -";
                            condition = "true";
                            statement = "[_player, 'nudge', ['y-']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(snudge_zp) {
                            displayName = "Z +";
                            condition = "true";
                            statement = "[_player, 'nudge', ['z+']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(snudge_zm) {
                            displayName = "Z -";
                            condition = "true";
                            statement = "[_player, 'nudge', ['z-']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(snudge_rp) {
                            displayName = "Turn right";
                            condition = "true";
                            statement = "[_player, 'nudge', ['r+']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                        class GVAR(snudge_rm) {
                            displayName = "Turn left";
                            condition = "true";
                            statement = "[_player, 'nudge', ['r-']] call btspk_speaker_fnc_clipped";
                            exceptions[] = {"isNotInside", "isNotSitting", "isNotSwimming"};
                        };
                };
