#!/usr/bin/env python3
"""Scan addons/audio/sounds/*.ogg and write addons/audio/playlist.hpp.

Arma only plays Ogg Vorbis. Convert other formats first, e.g.:
    ffmpeg -i song.mp3 -ac 1 -c:a libvorbis -q:a 5 song.ogg
(-ac 1 = mono, which Arma positions properly in 3D.)
"""
import json
import re
import sys
from pathlib import Path

ADDON = Path(__file__).resolve().parent.parent / "addons" / "audio"
SOUNDS = ADDON / "sounds"
OUT = ADDON / "playlist.hpp"
TITLES = SOUNDS / "titles.json"  # written by convert_music.py: file name -> real song title


def vorbis_duration(path):
    data = path.read_bytes()
    ident = data.find(b"\x01vorbis")
    if not data.startswith(b"OggS") or ident == -1:
        raise ValueError("not an Ogg Vorbis file")
    sample_rate = int.from_bytes(data[ident + 12:ident + 16], "little")
    last_page = data.rfind(b"OggS")
    granule = int.from_bytes(data[last_page + 6:last_page + 14], "little")
    return granule / sample_rate


def esc(text):
    return text.replace('"', '""')


def main():
    names = json.loads(TITLES.read_text(encoding="utf-8")) if TITLES.exists() else {}
    files = sorted(SOUNDS.glob("*.ogg"), key=lambda f: names.get(f.name, f.stem).lower())
    if not files:
        sys.exit(f"No .ogg files in {SOUNDS}")

    sounds, tracks, titles, durations = [], [], [], []
    for i, f in enumerate(files):
        try:
            duration = vorbis_duration(f)
        except ValueError as e:
            print(f"skipping {f.name}: {e}")
            continue
        cls = f"jbl_track_{i:03d}_" + re.sub(r"[^A-Za-z0-9_]", "_", f.stem)[:40]
        title = esc(names.get(f.name, f.stem))
        sounds.append(
            f"    class {cls} {{\n"
            f'        name = "{title}";\n'
            f'        sound[] = {{"\\z\\jbl\\addons\\audio\\sounds\\{esc(f.name)}", 1, 1}};\n'
            f"        titles[] = {{}};\n"
            f"    }};"
        )
        tracks.append(f'"{cls}"')
        titles.append(f'"{title}"')
        durations.append(f"{duration:.2f}")
        print(f"{duration:7.1f}s  {f.name}")

    OUT.write_text(
        "// Generated by tools/build_playlist.py - do not edit by hand\n"
        "class CfgSounds {\n    sounds[] = {};\n" + "\n".join(sounds) + "\n};\n\n"
        "class jbl_audio_playlist {\n"
        f"    tracks[] = {{{', '.join(tracks)}}};\n"
        f"    titles[] = {{{', '.join(titles)}}};\n"
        f"    durations[] = {{{', '.join(durations)}}};\n"
        "};\n"
    )
    print(f"Wrote {len(tracks)} tracks to {OUT}")


if __name__ == "__main__":
    main()
